# auth.py
# ---------------------------------------------------------------------------
# GitHub OAuth provider for the ExpenseTracker MCP server.
#
# How it works:
#   1. Claude Desktop discovers the server needs auth via the
#      /.well-known/oauth-authorization-server metadata endpoint (FastMCP
#      exposes this automatically once you attach an OAuthProvider).
#   2. Claude Desktop sends the user to GET /authorize → we redirect to GitHub.
#   3. GitHub redirects back to GET /callback?code=... → we exchange the code
#      for a GitHub access token, fetch the user's GitHub ID, then issue our
#      own short-lived JWT that we give back to Claude Desktop.
#   4. Every subsequent MCP tool call arrives with
#      "Authorization: Bearer <our JWT>" in the header.
#   5. FastMCP validates the JWT using our provider before the tool even runs.
#      The tool can then call get_current_user_id() to scope DB queries.
#
# Dependencies (add to your pyproject.toml / requirements.txt):
#   httpx          — async HTTP client for the GitHub API calls
#   python-jose    — JWT encode / decode
#   fastmcp >= 2.0 — OAuthProvider base class
#
# Environment variables you must set in Horizon's dashboard:
#   GITHUB_CLIENT_ID      — from github.com/settings/developers
#   GITHUB_CLIENT_SECRET  — from github.com/settings/developers
#   JWT_SECRET            — any long random string (use: openssl rand -hex 32)
#   SERVER_BASE_URL       — your public Horizon URL, e.g. https://xxx.fastmcp.app
# ---------------------------------------------------------------------------

import os
import time
import httpx

from jose import jwt, JWTError
from fastmcp.server.auth import OAuthProvider
from fastmcp.server.auth.types import (
    OAuthClientInfo,
    AuthorizationCode,
    AccessToken,
)

# ---------------------------------------------------------------------------
# Config — all sourced from environment variables, never hardcoded
# ---------------------------------------------------------------------------

GITHUB_CLIENT_ID     = os.environ["GITHUB_CLIENT_ID"]
GITHUB_CLIENT_SECRET = os.environ["GITHUB_CLIENT_SECRET"]
JWT_SECRET           = os.environ["JWT_SECRET"]
SERVER_BASE_URL      = os.environ["SERVER_BASE_URL"].rstrip("/")

GITHUB_AUTHORIZE_URL = "https://github.com/login/oauth/authorize"
GITHUB_TOKEN_URL     = "https://github.com/login/oauth/access_token"
GITHUB_USER_URL      = "https://api.github.com/user"

JWT_ALGORITHM        = "HS256"
JWT_EXPIRY_SECONDS   = 60 * 60 * 8   # 8 hours


# ---------------------------------------------------------------------------
# JWT helpers
# ---------------------------------------------------------------------------

def create_jwt(github_id: str, github_login: str) -> str:
    """Issue a signed JWT that encodes the user's GitHub identity."""
    payload = {
        "sub":    github_id,       # subject — stable numeric GitHub user ID
        "login":  github_login,    # human-readable GitHub username (for display)
        "iat":    int(time.time()),
        "exp":    int(time.time()) + JWT_EXPIRY_SECONDS,
    }
    return jwt.encode(payload, JWT_SECRET, algorithm=JWT_ALGORITHM)


def decode_jwt(token: str) -> dict:
    """
    Validate and decode a JWT we issued.
    Raises jose.JWTError if the token is invalid or expired.
    """
    return jwt.decode(token, JWT_SECRET, algorithms=[JWT_ALGORITHM])


# ---------------------------------------------------------------------------
# OAuthProvider implementation
# ---------------------------------------------------------------------------

class GitHubOAuthProvider(OAuthProvider):
    """
    FastMCP OAuth provider that delegates identity to GitHub.

    FastMCP calls these methods at the right points in the OAuth dance —
    you don't need to wire up any routes yourself.
    """

    # ------------------------------------------------------------------
    # Step 1 — Build the URL that Claude Desktop should send the user to
    # ------------------------------------------------------------------

    async def get_authorization_url(
        self,
        client_info: OAuthClientInfo,
        state: str,
        **kwargs,
    ) -> str:
        """
        Return the GitHub authorization URL.
        `state` is a CSRF token generated by FastMCP — always pass it through.
        """
        callback_url = f"{SERVER_BASE_URL}/callback"
        params = (
            f"client_id={GITHUB_CLIENT_ID}"
            f"&redirect_uri={callback_url}"
            f"&scope=read:user"          # we only need the user's ID
            f"&state={state}"
        )
        return f"{GITHUB_AUTHORIZE_URL}?{params}"

    # ------------------------------------------------------------------
    # Step 2 — GitHub redirected back; exchange the code for our own token
    # ------------------------------------------------------------------

    async def handle_callback(
        self,
        code: str,
        state: str,
        **kwargs,
    ) -> AccessToken:
        """
        Exchange the GitHub `code` for a GitHub access token, fetch the
        user's GitHub ID, then return our own signed JWT as the AccessToken.
        FastMCP will hand this token back to Claude Desktop.
        """
        async with httpx.AsyncClient() as client:

            # 1. Exchange code → GitHub access token
            token_resp = await client.post(
                GITHUB_TOKEN_URL,
                headers={"Accept": "application/json"},
                data={
                    "client_id":     GITHUB_CLIENT_ID,
                    "client_secret": GITHUB_CLIENT_SECRET,
                    "code":          code,
                },
            )
            token_resp.raise_for_status()
            github_token = token_resp.json()["access_token"]

            # 2. Use GitHub token → fetch user profile
            user_resp = await client.get(
                GITHUB_USER_URL,
                headers={
                    "Authorization": f"Bearer {github_token}",
                    "Accept":        "application/vnd.github+json",
                },
            )
            user_resp.raise_for_status()
            user = user_resp.json()

        # 3. Issue our own JWT (we never store the GitHub token)
        our_jwt = create_jwt(
            github_id    = str(user["id"]),
            github_login = user["login"],
        )

        return AccessToken(
            token      = our_jwt,
            token_type = "bearer",
            expires_in = JWT_EXPIRY_SECONDS,
        )

    # ------------------------------------------------------------------
    # Step 3 — Validate on every incoming tool call
    # ------------------------------------------------------------------

    async def validate_token(self, token: str) -> dict:
        """
        Called by FastMCP before every tool invocation.
        Must return the decoded payload (which FastMCP attaches to the
        request context) or raise an exception to reject the call.
        """
        try:
            return decode_jwt(token)
        except JWTError as exc:
            # FastMCP catches this and returns a 401 to the client
            raise ValueError(f"Invalid or expired token: {exc}") from exc